---
title: "Web Sraping"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Scraping James (LOL)

```{r}
library(tidyverse)
library(rvest)
library(knitr)
```



```{r}
url<-read_html('https://es.wikipedia.org/wiki/Anexo:Partidos_de_la_selecci%C3%B3n_de_f%C3%BAtbol_de_Colombia#A%C3%B1os_2020_-_2029')

marcadores<-url%>%
  html_nodes('td:nth-child(6) > b')%>%
  html_text()%>%
  tbl_df()%>%
  filter(str_detect(value,':'))%>%
  rename('Marcadores'=value)

Fecha<-url%>%
  html_nodes('td:nth-child(3)')%>%
  html_text()%>%
  tbl_df()%>%
  filter(str_detect(value,'de'))%>%
  mutate(value=str_replace_all(value,"\n|\r", ""))%>%
  mutate(value=str_replace_all(value, "[^[:alnum:]]", " "))%>%
  rename('Fecha'=value)
  
rival<-url%>%
  html_nodes('td:nth-child(5) > a')%>%
  html_text()%>%
  tbl_df()%>%
  rename("Rival"=value)

base_colombia<-data.frame(Fecha,rival,marcadores)
base_partidos<-base_colombia%>%
  filter(str_detect(Fecha,'2019|2020'))%>%
  separate(Marcadores,c('Marcador_Colombia','Marcador_Rival'),sep=':',fill='right')%>%
  mutate(Marcador_Colombia = as.numeric(Marcador_Colombia),
         Marcador_Rival = as.numeric(Marcador_Rival),
         Resultado = case_when(Marcador_Colombia>Marcador_Rival~"Gano",
                               Marcador_Colombia<Marcador_Rival~"Perdió",
                               Marcador_Colombia==Marcador_Rival~"Empato"))


base_partidos%>%
  kable(format = 'markdown', caption = 'Scraping Partidos')
```





